import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { motion } from "framer-motion";
import { ArrowRight, Building2, Mail, MapPin, Sparkles, Loader2, Check, ChevronsUpDown, Lock } from "lucide-react";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
} from "@/components/ui/command";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import { cn } from "@/lib/utils";
import { useForm, Controller } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import * as z from "zod";
import { supabase } from "@/supabase";
import { useAuth } from "@/lib/auth-context";
import { toast } from "sonner";
import { useState, useRef, useEffect } from "react";
import { getDashboardPathForRole, resolveUserRole } from "@/lib/auth-role";
import { InternationalPhoneInput } from "@/components/InternationalPhoneInput";
import { INTERNATIONAL_PHONE_REGEX, cleanPhoneInput, normalizeToE164Phone } from "@/lib/phone";
import { postAuthDestination } from "@/lib/auth-redirect";

const signupSchema = z.object({
  gymName: z.string().min(2, "Gym name must be at least 2 characters"),
  city: z.string().min(2, "City must be at least 2 characters"),
  email: z.string().email("Please enter a valid email address"),
  mobile: z
    .string()
    .transform((value) => cleanPhoneInput(value))
    .refine((value) => INTERNATIONAL_PHONE_REGEX.test(value), "Please enter a valid international mobile number"),
  password: z.string().min(6, "Password must be at least 6 characters"),
});

const loginSchema = z.object({
  identifier: z.string().min(1, "Email or Mobile Number is required"),
  password: z.string().min(1, "Password is required"),
});

type SignupFormValues = z.infer<typeof signupSchema>;
type LoginFormValues = z.infer<typeof loginSchema>;

const INDIAN_CITIES = [
  "Mumbai", "Delhi", "Bangalore", "Hyderabad", "Ahmedabad", "Chennai", "Kolkata", "Surat", 
  "Pune", "Jaipur", "Lucknow", "Kanpur", "Nagpur", "Indore", "Thane", "Bhopal", 
  "Visakhapatnam", "Pimpri-Chinchwad", "Patna", "Vadodara", "Ghaziabad", "Ludhiana", 
  "Agra", "Nashik", "Faridabad", "Meerut", "Rajkot", "Kalyan-Dombivli", "Vasai-Virar", 
  "Varanasi", "Srinagar", "Aurangabad", "Dhanbad", "Amritsar", "Navi Mumbai", 
  "Allahabad", "Ranchi", "Howrah", "Jabalpur", "Gwalior", "Vijayawada", "Jodhpur", 
  "Madurai", "Raipur", "Kota", "Guwahati", "Chandigarh", "Solapur", "Hubli-Dharwad", 
  "Bareilly", "Moradabad", "Mysore", "Gurgaon", "Aligarh", "Jalandhar", "Tiruchirappalli", 
  "Bhubaneswar", "Salem", "Mira-Bhayandar", "Warangal", "Guntur", "Bhiwandi", 
  "Saharanpur", "Gorakhpur", "Bikaner", "Amravati", "Noida", "Jamshedpur", "Bhilai", 
  "Cuttack", "Firozabad", "Kochi", "Nellore", "Bhavnagar", "Dehradun", "Durgapur", 
  "Asansol", "Rourkela", "Nanded", "Kolhapur", "Ajmer", "Gulbarga", "Jamnagar", 
  "Ujjain", "Loni", "Siliguri", "Jhansi", "Ulhasnagar", "Nellore", "Jammu", 
  "Sangli-Miraj & Kupwad", "Belgaum", "Mangalore", "Ambattur", "Tirunelveli", 
  "Malegaon", "Gaya", "Jalgaon", "Udaipur", "Maheshtala"
].sort();

export const Route = createFileRoute("/signup")({
  head: () => ({
    meta: [
      { title: "Join Gymphony — Start Your Free Trial" },
      {
        name: "description",
        content: "Create your gym account on Gymphony and start growing today.",
      },
    ],
  }),
  component: SignupPage,
});

function SignupPage() {
  const navigate = useNavigate();
  const urlParams = typeof window !== 'undefined' ? new URLSearchParams(window.location.search) : new URLSearchParams();
  // Bulk-onboard / locked-identity invite params (generated by BulkOnboard.tsx).
  // `token` is the pending members.id (claim token); `phone` is the number the
  // owner registered and MUST be locked on this form.
  const inviteToken = urlParams.get("token") || urlParams.get("member_slot");
  const inviteGymId = urlParams.get("gym_id");
  const invitePhoneParam = urlParams.get("phone");
  const isLockedInvite = Boolean(invitePhoneParam && (inviteToken || inviteGymId));
  const [isLoading, setIsLoading] = useState(false);
  const [activeTab, setActiveTab] = useState<"login" | "signup">("signup");
  const authControllerRef = useRef<AbortController | null>(null);
  const { session, role, roleResolved } = useAuth();

  // A signed-in user on the join page is routed to their saved QR destination if
  // any, else to their dashboard (parity with the previous behaviour).
  useEffect(() => {
    if (session && roleResolved && role) {
      const target = postAuthDestination();
      if (target) {
        window.location.assign(target);
        return;
      }
      navigate({ to: getDashboardPathForRole(role), replace: true });
    }
    return () => {
      if (authControllerRef.current) {
        authControllerRef.current.abort();
      }
    };
  }, [session, role, roleResolved, navigate]);

  const signupForm = useForm<SignupFormValues>({
    resolver: zodResolver(signupSchema),
    defaultValues: {
      gymName: "",
      city: "",
      email: "",
      mobile: "",
      password: "",
    },
  });

  const loginForm = useForm<LoginFormValues>({
    resolver: zodResolver(loginSchema),
    defaultValues: {
      identifier: "",
      password: "",
    },
  });

  const [cityOpen, setCityOpen] = useState(false);

  // Locked-identity invite: force the Sign Up tab and pre-fill the phone from the
  // invite link. The phone input is rendered disabled below so it can't change.
  useEffect(() => {
    if (isLockedInvite && invitePhoneParam) {
      setActiveTab("signup");
      const normalized = normalizeToE164Phone(invitePhoneParam, "+91") || invitePhoneParam;
      signupForm.setValue("mobile", normalized, { shouldValidate: true });
      // City is a gym-owner field; not relevant for an invited member. Set a
      // placeholder so the shared schema validates, and hide the field below.
      signupForm.setValue("city", "Member", { shouldValidate: true });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isLockedInvite, invitePhoneParam]);

  const onSignupSubmit = async (data: SignupFormValues) => {
    if (authControllerRef.current) {
      authControllerRef.current.abort();
    }
    authControllerRef.current = new AbortController();

    setIsLoading(true);
    try {
      // Unique per-tenant gym id (was a hardcoded constant shared by ALL owners
      // — a cross-tenant data-isolation bug). The real gym_settings row is
      // provisioned via ensure_gym_settings() below using this same id.
      let ownerGymId: string = crypto.randomUUID();

      if (inviteToken || inviteGymId) {
        const { data: signUpData, error: signUpError } = await supabase.auth.signUp({
          email: data.email,
          password: data.password,
          options: { data: { role: "member" } },
        });

        if (signUpError) throw signUpError;

        const newUserId = signUpData.user?.id;
        if (!newUserId) throw new Error("Failed to create auth user");

        // The phone is locked to the invite — never trust a client-changed value.
        const lockedPhone = isLockedInvite && invitePhoneParam
          ? (normalizeToE164Phone(invitePhoneParam, "+91") || invitePhoneParam)
          : data.mobile;

        if (inviteToken) {
          // Claim the pending_signup slot the owner created in BulkOnboard:
          // tie this auth user to that exact row and activate the membership.
          const updates: any = {
            auth_user_id: newUserId,
            status: "Active",
            full_name: data.gymName || data.email.split("@")[0],
            mobile_number: lockedPhone,
            phone: lockedPhone,
          };
          if (inviteGymId) updates.gym_id = inviteGymId;

          const { error: updateError } = await supabase
            .from("members")
            .update(updates)
            .eq("id", inviteToken);

          if (updateError) {
            const { error: insertError } = await supabase
              .from("members")
              .upsert([
                {
                  id: newUserId,
                  auth_user_id: newUserId,
                  full_name: data.gymName || data.email.split("@")[0],
                  mobile_number: lockedPhone,
                  phone: lockedPhone,
                  status: "Active",
                  gym_id: inviteGymId || null,
                  joining_date: new Date().toISOString().split("T")[0],
                },
              ], { onConflict: "id" });

            if (insertError) {
              if (String(insertError.message || "").toLowerCase().includes("duplicate") || String(insertError.code || "").includes("23505")) {
                toast.error("This account already exists. Please log in instead.");
                return;
              }
              throw insertError;
            }
          }
        } else if (inviteGymId) {
          const { error: insertError } = await supabase
            .from("members")
            .upsert([
              {
                id: newUserId,
                auth_user_id: newUserId,
                full_name: data.gymName || data.email.split("@")[0],
                mobile_number: lockedPhone,
                phone: lockedPhone,
                status: "Active",
                gym_id: inviteGymId,
                joining_date: new Date().toISOString().split("T")[0],
              },
            ], { onConflict: "id" });

          if (insertError) {
            if (String(insertError.message || "").toLowerCase().includes("duplicate") || String(insertError.code || "").includes("23505")) {
              toast.error("This account already exists. Please log in instead.");
              return;
            }
            throw insertError;
          }
        }

        signupForm.reset();
        // Session-aware: if email confirmation is OFF, signUp returns a session →
        // go straight to the member dashboard. If ON (no session), send them to
        // the member login to sign in after confirming — no bounce loop.
        if (signUpData.session) {
          toast.success("✅ Account created. Your membership is now active.");
          navigate({ to: "/member-dashboard", replace: true });
        } else {
          toast.success("✅ Account created. Please confirm your email, then log in.");
          navigate({ to: "/member-login", replace: true });
        }
        return;
      }

      const { data: authData, error: authError } = await supabase.auth.signUp({
        email: data.email,
        password: data.password,
        options: { data: { role: "owner", gym_id: ownerGymId } },
      });

      if (authError) {
        const authMessage = String(authError.message || "").toLowerCase();
        if (authError.status === 429 || authMessage.includes("rate limit") || authMessage.includes("over_email_send_rate_limit")) {
          console.warn("Owner signup hit email rate limit; checking existing profile for direct redirect.", authError);

          const { data: existingProfile, error: existingProfileError } = await supabase
            .from("profiles")
            .select("id, role, gym_id")
            .eq("email", data.email)
            .maybeSingle();

          if (existingProfileError) {
            console.error("Rate-limit fallback profile lookup failed:", existingProfileError);
          }

          if (existingProfile?.role === "owner") {
            toast.success("Account already exists — taking you to your dashboard.");
            navigate({ to: getDashboardPathForRole("owner"), replace: true });
            return;
          }

          toast.error("Too many attempts. Please wait a moment and try again, or log in.");
          return;
        }

        if (authMessage.includes("already") || authMessage.includes("exists") || authMessage.includes("registered")) {
          toast.error("You're already registered. Please log in instead.");
          setActiveTab("login");
          return;
        }
        throw authError;
      }

      if (!authData.user?.id) {
        throw new Error("Failed to create auth user");
      }

      // Provision this owner's gym_settings row (unique id) + 7-day trial via the
      // SECURITY DEFINER RPC. Idempotent. If the session isn't ready yet the
      // dashboard re-runs ensure_gym_settings on load, so signup never blocks.
      try {
        const { data: ensuredId, error: ensureErr } = await supabase.rpc("ensure_gym_settings", {
          p_gym_id: ownerGymId,
          p_gym_name: data.gymName,
          p_email: data.email,
        });
        if (ensureErr) throw ensureErr;
        if (ensuredId) ownerGymId = ensuredId as string;
      } catch (e) {
        console.warn("ensure_gym_settings failed (dashboard will retry):", e);
      }

      const ownerProfilePayload = {
        id: authData.user.id,
        role: "owner",
        gym_id: ownerGymId,
        gym_name: data.gymName,
        city: data.city,
        email: data.email,
        mobile_number: data.mobile,
      };

      console.log("Sending data:", ownerProfilePayload);

      const { error: ownerProfileError } = await supabase
        .from("profiles")
        .upsert([ownerProfilePayload], { onConflict: "id" })
        .abortSignal(authControllerRef.current.signal);

      if (ownerProfileError) {
        console.error("Owner profile upsert failed:", ownerProfileError);
        const profileMessage = String(ownerProfileError.message || "").toLowerCase();
        if (profileMessage.includes("duplicate") || String(ownerProfileError.code || "").includes("23505")) {
          toast.error("You're already registered. Please log in instead.");
          setActiveTab("login");
          return;
        }
        throw ownerProfileError;
      }

      const { error: profileError } = await supabase
        .from("gym_profiles")
        .upsert(
          [
            {
              id: authData.user.id,
              role: "owner",
              gym_id: ownerGymId,
              gym_name: data.gymName,
              city: data.city,
              email: data.email,
              phone: data.mobile,
              mobile_number: data.mobile,
            },
          ],
          { onConflict: "id" }
        )
        .abortSignal(authControllerRef.current.signal);

      if (profileError) {
        console.error("Gym profile upsert failed:", profileError);
        const profileMessage = String(profileError.message || "").toLowerCase();
        if (profileMessage.includes("duplicate") || String(profileError.code || "").includes("23505")) {
          toast.error("You're already registered. Please log in instead.");
          setActiveTab("login");
          return;
        }
        throw profileError;
      }

      signupForm.reset();
      // Session-aware redirect (same as the main auth flow): only go to the
      // dashboard when a session exists; otherwise prompt to confirm email.
      if (authData.session) {
        toast.success("✅ Account created! Setting up your dashboard…");
        navigate({ to: getDashboardPathForRole("owner"), replace: true });
      } else {
        toast.success("✅ Account created! Please check your email to confirm, then log in.");
        setActiveTab("login");
      }
    } catch (error: any) {
      if (
        error.name === "AbortError" ||
        error.message?.includes("abort") ||
        error.message?.includes("Lock broken")
      ) {
        console.warn("Silent fetch error in onSignupSubmit:", error);
        return;
      }
      console.error("Signup error:", error);
      toast.error(error?.message || "Signup failed. Please try again.");
    } finally {
      setIsLoading(false);
    }
  };

  const onLoginSubmit = async (data: LoginFormValues) => {
    if (authControllerRef.current) {
      authControllerRef.current.abort();
    }
    authControllerRef.current = new AbortController();

    setIsLoading(true);
    try {
      let loginEmail = data.identifier;

      // Allow logging in with an international mobile number: look up the email.
      const normalizedMobile = normalizeToE164Phone(data.identifier, "");
      if (normalizedMobile) {
        const { data: profile, error: profileError } = await supabase
          .from("gym_profiles")
          .select("email")
          .or(`mobile_number.eq.${normalizedMobile},phone.eq.${normalizedMobile}`)
          .abortSignal(authControllerRef.current.signal)
          .maybeSingle();

        if (
          profileError?.name === "AbortError" ||
          profileError?.message?.includes("abort") ||
          profileError?.message?.includes("Lock broken")
        ) {
          return;
        }
        if (profileError || !profile?.email) {
          toast.error("No account found with this mobile number.");
          return;
        }
        loginEmail = profile.email;
      }

      const { data: loginData, error } = await supabase.auth.signInWithPassword({
        email: loginEmail,
        password: data.password,
      });

      if (error) {
        const msg = String(error.message || "").toLowerCase();
        toast.error(
          msg.includes("invalid login credentials")
            ? "Invalid credentials. Please check your email/mobile and password."
            : msg.includes("not confirmed")
              ? "Please confirm your email first — check your inbox for the verification link."
              : error.message || "Login failed. Please try again."
        );
        return;
      }

      const user = loginData?.user;
      if (!user) {
        toast.error("Login failed. Please try again.");
        return;
      }

      // Same robust, metadata-aware resolver as the main login. AuthRedirects is
      // the safety net if the default is ever wrong for this shared join page.
      const resolvedRole = (await resolveUserRole(user)) ?? "owner";
      toast.success("✅ Logged in successfully!");
      loginForm.reset();
      const target = postAuthDestination();
      if (target) {
        window.location.assign(target);
        return;
      }
      navigate({ to: getDashboardPathForRole(resolvedRole), replace: true });
    } catch (error: any) {
      if (
        error.name === "AbortError" ||
        error.message?.includes("abort") ||
        error.message?.includes("Lock broken")
      ) {
        console.warn("Silent fetch error in onLoginSubmit:", error);
        return;
      }
      console.error("Login error:", error);
      toast.error(error?.message || "Login failed. Please try again.");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-background text-foreground flex flex-col">
      <Navbar />
      
      <main className="grow relative flex items-center justify-center px-6 py-24 md:py-32 overflow-hidden">
        {/* Background orbs for glassmorphism effect */}
        <div className="glow-orb -top-20 left-1/4 h-72 w-72 bg-primary-glow opacity-30" />
        <div className="glow-orb bottom-20 right-1/4 h-96 w-96 bg-primary opacity-20" />
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_center,color-mix(in_oklab,var(--color-primary-glow)_10%,transparent),transparent_70%)]" />

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          className="relative w-full max-w-lg"
        >
          {/* Form Container with Glassmorphism */}
          <div className="relative overflow-hidden rounded-[2.5rem] border border-white/10 bg-white/5 p-8 md:p-12 shadow-2xl backdrop-blur-xl">
            {/* Inner glow effect */}
            <div className="absolute -top-24 -right-24 h-48 w-48 rounded-full bg-primary/20 blur-3xl" />
            
            <div className="relative space-y-8">
              <div className="text-center space-y-4">
                <motion.div 
                  initial={{ scale: 0.9 }}
                  animate={{ scale: 1 }}
                  className="inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/10 px-4 py-1.5 text-xs font-medium text-primary backdrop-blur"
                >
                  <Sparkles className="h-3.5 w-3.5" />
                  <span>Join the future of gym management</span>
                </motion.div>
                
                <h1 className="font-display text-4xl font-bold tracking-tight md:text-5xl">
                  {activeTab === "signup" ? (
                    isLockedInvite ? (
                      <>Activate <span className="text-gradient-brand">Membership</span></>
                    ) : (
                      <>Create <span className="text-gradient-brand">My Gym</span></>
                    )
                  ) : (
                    <>Welcome <span className="text-gradient-brand">Back</span></>
                  )}
                </h1>
              </div>

              <Tabs value={activeTab} onValueChange={(v) => setActiveTab(v as any)} className="w-full">
                <TabsList className="grid w-full grid-cols-2 bg-white/5 border border-white/10 p-1 h-12 rounded-xl mb-8">
                  <TabsTrigger value="signup" className="rounded-lg data-[state=active]:bg-primary data-[state=active]:text-white">Sign Up</TabsTrigger>
                  <TabsTrigger value="login" className="rounded-lg data-[state=active]:bg-primary data-[state=active]:text-white">Log In</TabsTrigger>
                </TabsList>

                <TabsContent value="signup">
                  <form className="space-y-6" onSubmit={signupForm.handleSubmit(onSignupSubmit)}>
                    <div className="space-y-4">
                      <div className="space-y-2 group">
                        <Label htmlFor="gymName" className="text-sm font-medium text-foreground/80 group-focus-within:text-primary transition-colors">{isLockedInvite ? "Your Full Name" : "Gym Name"}</Label>
                        <div className="relative">
                          <Building2 className="absolute left-4 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground group-focus-within:text-primary transition-colors" />
                          <Input
                            id="gymName"
                            {...signupForm.register("gymName")}
                            placeholder={isLockedInvite ? "e.g. Rohit Sharma" : "e.g. Iron Paradise"}
                            className={`h-12 pl-11 bg-white/5 border-white/10 focus:border-primary/50 focus:ring-primary/20 transition-all rounded-xl ${signupForm.formState.errors.gymName ? 'border-red-500' : ''}`}
                          />
                        </div>
                        {signupForm.formState.errors.gymName && <p className="text-xs text-red-500">{signupForm.formState.errors.gymName.message}</p>}
                      </div>

                      {!isLockedInvite && (
                      <div className="space-y-2 group">
                        <Label htmlFor="city" className="text-sm font-medium text-foreground/80 group-focus-within:text-primary transition-colors">City</Label>
                        <div className="relative">
                          <Controller
                            name="city"
                            control={signupForm.control}
                            render={({ field }) => (
                              <Popover open={cityOpen} onOpenChange={setCityOpen}>
                                <PopoverTrigger asChild>
                                  <Button
                                    variant="outline"
                                    role="combobox"
                                    className={cn(
                                      "w-full h-12 pl-11 justify-between bg-white/5 border-white/10 hover:bg-white/10 hover:text-foreground text-left font-normal rounded-xl transition-all",
                                      !field.value && "text-muted-foreground",
                                      signupForm.formState.errors.city && "border-red-500"
                                    )}
                                  >
                                    <MapPin className="absolute left-4 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground group-focus-within:text-primary transition-colors" />
                                    {field.value || "Select city..."}
                                    <ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 opacity-50" />
                                  </Button>
                                </PopoverTrigger>
                                <PopoverContent className="w-(--radix-popover-trigger-width) p-0 bg-slate-900 border-white/10 backdrop-blur-xl">
                                  <Command className="bg-transparent">
                                    <CommandInput placeholder="Search city..." className="h-10 text-white" />
                                    <CommandList className="max-h-60 overflow-y-auto">
                                      <CommandEmpty className="text-white/60">No city found.</CommandEmpty>
                                      <CommandGroup className="text-white">
                                        {INDIAN_CITIES.map((city) => (
                                          <CommandItem
                                            key={city}
                                            value={city}
                                            onSelect={(val) => {
                                              signupForm.setValue("city", val, { shouldValidate: true });
                                              setCityOpen(false);
                                            }}
                                            className="text-white hover:bg-white/10 cursor-pointer"
                                          >
                                            <Check className={cn("mr-2 h-4 w-4", field.value === city ? "opacity-100" : "opacity-0")} />
                                            {city}
                                          </CommandItem>
                                        ))}
                                      </CommandGroup>
                                    </CommandList>
                                  </Command>
                                </PopoverContent>
                              </Popover>
                            )}
                          />
                        </div>
                        {signupForm.formState.errors.city && <p className="text-xs text-red-500">{signupForm.formState.errors.city.message}</p>}
                      </div>
                      )}

                      <div className="space-y-2 group">
                        <Label htmlFor="email" className="text-sm font-medium text-foreground/80 group-focus-within:text-primary transition-colors">Email Address</Label>
                        <div className="relative">
                          <Mail className="absolute left-4 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground group-focus-within:text-primary transition-colors" />
                          <Input
                            id="email"
                            type="email"
                            {...signupForm.register("email")}
                            placeholder="owner@yourgym.com"
                            className={`h-12 pl-11 bg-white/5 border-white/10 focus:border-primary/50 focus:ring-primary/20 transition-all rounded-xl ${signupForm.formState.errors.email ? 'border-red-500' : ''}`}
                          />
                        </div>
                        {signupForm.formState.errors.email && <p className="text-xs text-red-500">{signupForm.formState.errors.email.message}</p>}
                      </div>

                      <Controller
                        control={signupForm.control}
                        name="mobile"
                        render={({ field }) => (
                          <InternationalPhoneInput
                            id="mobile"
                            label="Mobile Number"
                            value={field.value}
                            onChange={field.onChange}
                            placeholder="e.g. +919876543210"
                            defaultCountryCode="+91"
                            error={signupForm.formState.errors.mobile?.message}
                            className="group"
                            inputClassName="bg-white/5 border-white/10 focus:border-primary/50 focus:ring-primary/20"
                            disabled={isLockedInvite}
                          />
                        )}
                      />
                      {isLockedInvite && (
                        <p className="flex items-center gap-1.5 text-xs text-primary/80 -mt-2">
                          <Lock className="h-3 w-3" />
                          Your number is set by your gym and can’t be changed — it secures your membership identity.
                        </p>
                      )}

                      <div className="space-y-2 group">
                        <Label htmlFor="password-signup" className="text-sm font-medium text-foreground/80 group-focus-within:text-primary transition-colors">Password</Label>
                        <div className="relative">
                          <Lock className="absolute left-4 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground group-focus-within:text-primary transition-colors" />
                          <Input
                            id="password-signup"
                            type="password"
                            {...signupForm.register("password")}
                            placeholder="••••••••"
                            className={`h-12 pl-11 bg-white/5 border-white/10 focus:border-primary/50 focus:ring-primary/20 transition-all rounded-xl ${signupForm.formState.errors.password ? 'border-red-500' : ''}`}
                          />
                        </div>
                        {signupForm.formState.errors.password && <p className="text-xs text-red-500">{signupForm.formState.errors.password.message}</p>}
                      </div>
                    </div>

                    <Button 
                      type="submit"
                      disabled={isLoading}
                      className="w-full h-14 rounded-xl bg-gradient-brand text-primary-foreground font-bold text-lg shadow-glow hover:shadow-primary/40 hover:-translate-y-0.5 transition-all group disabled:opacity-70"
                    >
                      {isLoading ? <Loader2 className="h-5 w-5 animate-spin" /> : (
                        <>Create My Gym <ArrowRight className="ml-2 h-5 w-5 transition-transform group-hover:translate-x-1" /></>
                      )}
                    </Button>
                  </form>
                </TabsContent>

                <TabsContent value="login">
                  <form className="space-y-6" onSubmit={loginForm.handleSubmit(onLoginSubmit)}>
                    <div className="space-y-4">
                      <div className="space-y-2 group">
                        <Label htmlFor="identifier-login" className="text-sm font-medium text-foreground/80 group-focus-within:text-primary transition-colors">Email or Mobile Number</Label>
                        <div className="relative">
                          <Mail className="absolute left-4 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground group-focus-within:text-primary transition-colors" />
                          <Input
                            id="identifier-login"
                            {...loginForm.register("identifier")}
                            placeholder="e.g. 9876543210 or owner@gym.com"
                            className={`h-12 pl-11 bg-white/5 border-white/10 focus:border-primary/50 focus:ring-primary/20 transition-all rounded-xl ${loginForm.formState.errors.identifier ? 'border-red-500' : ''}`}
                          />
                        </div>
                        {loginForm.formState.errors.identifier && <p className="text-xs text-red-500">{loginForm.formState.errors.identifier.message}</p>}
                      </div>

                      <div className="space-y-2 group">
                        <Label htmlFor="password-login" className="text-sm font-medium text-foreground/80 group-focus-within:text-primary transition-colors">Password</Label>
                        <div className="relative">
                          <Lock className="absolute left-4 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground group-focus-within:text-primary transition-colors" />
                          <Input
                            id="password-login"
                            type="password"
                            {...loginForm.register("password")}
                            placeholder="••••••••"
                            className={`h-12 pl-11 bg-white/5 border-white/10 focus:border-primary/50 focus:ring-primary/20 transition-all rounded-xl ${loginForm.formState.errors.password ? 'border-red-500' : ''}`}
                          />
                        </div>
                        {loginForm.formState.errors.password && <p className="text-xs text-red-500">{loginForm.formState.errors.password.message}</p>}
                      </div>
                    </div>

                    <Button 
                      type="submit"
                      disabled={isLoading}
                      className="w-full h-14 rounded-xl bg-gradient-brand text-primary-foreground font-bold text-lg shadow-glow hover:shadow-primary/40 hover:-translate-y-0.5 transition-all group disabled:opacity-70"
                    >
                      {isLoading ? <Loader2 className="h-5 w-5 animate-spin" /> : (
                        <>Log In <ArrowRight className="ml-2 h-5 w-5 transition-transform group-hover:translate-x-1" /></>
                      )}
                    </Button>
                  </form>
                </TabsContent>
              </Tabs>

              <p className="text-center text-xs text-muted-foreground">
                By continuing, you agree to our{" "}
                <a href="#" className="underline hover:text-primary">Terms of Service</a>
                {" "}and{" "}
                <a href="#" className="underline hover:text-primary">Privacy Policy</a>.
              </p>
            </div>
          </div>
        </motion.div>
      </main>

      <Footer />
    </div>
  );
}
